[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', 'node_modules']
fs_permissions = [{ access = "read-write", path = "./"}]
optimizer = true
optimizer_runs = 200
via_ir = true


[rpc_endpoints]
default_network = "http://127.0.0.1:8545"

# Hedera Networks (EVM Compatible)
hedera_testnet = "https://testnet.hashio.io/api"
hedera_mainnet = "https://mainnet.hashio.io/api"

# Ethereum Networks
mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
sepolia = "https://small-radial-replica.ethereum-sepolia.quiknode.pro/47ca53cab2d39a5fabf79a2e1f421f4c15c6de80/"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrumSepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimismSepolia = "https://opt-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygonMumbai = "https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygonZkEvm = "https://zkevm-rpc.com"
polygonZkEvmTestnet = "https://rpc.public.zkevm-test.net"
gnosis = "https://rpc.gnosischain.com"
chiado = "https://rpc.chiadochain.net"
base = "https://mainnet.base.org"
baseSepolia = "https://sepolia.base.org"
scrollSepolia = "https://sepolia-rpc.scroll.io"
scroll = "https://rpc.scroll.io"
pgn = "https://rpc.publicgoods.network"
pgnTestnet = "https://sepolia.publicgoods.network"


localhost = "http://127.0.0.1:8545"

[etherscan]
# Hedera Networks
hedera_testnet = { key = "${HASHSCAN_API_KEY}", url = "https://hashscan.io/testnet/api" }
hedera_mainnet = { key = "${HASHSCAN_API_KEY}", url = "https://hashscan.io/api" }

# Ethereum
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# Base
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
baseSepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# Arbitrum
arbitrum = { key = "${ETHERSCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
arbitrumSepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }

# Optimism
optimism = { key = "${ETHERSCAN_API_KEY}", url = "https://api-optimistic.etherscan.io/api" }
optimismSepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia-optimistic.etherscan.io/api" }

# Polygon
polygon = { key = "${ETHERSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
polygonMumbai = { key = "${ETHERSCAN_API_KEY}" }



[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
bracket_spacing = true
int_types = "long"




# See more config options https://book.getfoundry.sh/reference/config/overview